### ISSUE TITLE
Less ambitious, less rubbish 1.12 release

### ISSUE THREAD

**Issue by LunNova** [MinimallyCorrect/TickThreading#1248]
Tasks:
- [x] Split javassist patching implementation into separate project
  - [x] Split non-minecraft code into [JavaPatcher](/nallar/JavaPatcher)
  - [x] Split minecraft-specific code into [ModPatcher](/nallar/ModPatcher)
- [x] Mixin implementation in nallar/JavaPatcher. nallar/Javapatcher#2
  - [x] Mixin implementation in [Mixin](/nallar/Mixin) nallar/Mixin#1
  - [x] Mixin transformations in [ModPatcherGradle](/nallar/ModPatcherGradle)
- [x] ~~Improve performance in ModPatcher by avoiding re-transforming~~ nallar/ModPatcher#10
- [x] Implement old profiling features in separate mod. nallar/TickProfiler#22
- [ ] Start from scratch, bring in some important features. Avoid feature creep
  - [x] Implement variant system (core/threaded for now, should be extensible)
  - [ ] Implement per-world threading
  - [ ] Implement deadlock detector
  - [ ] async/threaded chunkloading improvements
    - [ ] Fix the bloody stupid chunkloading when you world.get<anything> with coords an unloaded chunk
    - [ ] Chunkloading cache which actually works
  - [ ] Entity collision performance fixes
  - [x] Fix FMLCommonHandler.getEffectiveSide -> hardcode as always running on server
  - [ ] Avoid slow operations on TE/Entity lists. See [TickManager.batchRemove(Tile)Entities](https://github.com/nallar/TickThreading/blob/2a6554e7ece1a67189f0834124bebd43a74c35cf/src/main/java/nallar/tickthreading/minecraft/TickManager.java#L171)
  - [ ] Fix poor `World.getPersistentChunks` performance

**Comment by MrVoltz** [comment]
Glad to hear you're coming back! I'm still sticking with your 1.5.2 release and fix everything myself :D.

**Comment by Vycraftujto** [comment]
Wooow welcome back!!! We are so glad your coming whit 1.8 !!!!

**Comment by LunNova** [comment]
Sorry about the spam when I closed all the issues there.

I've closed all the old issues, as I won't be doing any further work on older MC versions.

**Comment by LunNova** [comment]
I've added a task list with basic plans for the first preview release. Have I missed any features people depend on?

I want to try to avoid adding too many features. TT ended up with a LOT of feature creep.

For example, in the new version TT will not have its own profiling, as the same features will be in TickProfiler. I'll need to work on improving TickProfiler's profiling features to match what used to be in TT.

**Comment by Slind14** [comment]
I'm not sure if you see a solution, anyways, the chunk unloading tends to be more intense than the load once the active/ticking tile entities hit +15k in the world. They are all stored in an array list and on chunk unload they are being removed. But to keep in mind, on tick update minecraft is iterating over the list, so other collections don't make sense either.
On servers with +25k active tile ents we have run good with a list set combination. 
You gave us the idea about this some time back, not sure if you remember :)
https://gist.github.com/Slind14/da64506db693f060afdd
https://gist.github.com/Slind14/1531aa0d5db944cc61b0

What I could think of would be to run the chunkunloading only every n ticks for all chunks together, so that it only needs to go over the list once instead of for every chunk.

Anyways its all not about multi threading.

Regarding the collision fix, wouldn't make sense to be kept in separated mod, or would you use multithreading for it?

**Comment by LunNova** [comment]
> I'm not sure if you see a solution, anyways, the chunk unloading tends to be more intense than the load once the active/ticking tile entities hit +15k in the world.

Old TT did as few operations as possible against those lists, and batched any additions/removals to them to once per tick using addAll/removeAll, which is much more efficient than separate remove calls. See [TickManager.batchRemove(Tile)Entities](https://github.com/nallar/TickThreading/blob/2a6554e7ece1a67189f0834124bebd43a74c35cf/src/main/java/nallar/tickthreading/minecraft/TickManager.java#L171). Added to task list.

> Regarding the collision fix, wouldn't make sense to be kept in separated mod, or would you use multithreading for it?

Fair point. I had this fix in old versions of TT as it's reasonably easy and helps performance a lot. Spigot sort of did the same thing, but not as well/aggressively. It's not really threading related though.

Reopened #107. The name currently isn't representative of what TT aims to do. Performance improvements, some but not all due to threading.

My "NTweaks" mod is mainly a rushed stop-gap measure because I was running a server for a few friends and there were approximately infinite squid spawning, and I couldn't change dimensions more than a few times due to memory leaks. I'm surprised it's been useful for other people. New TT will be using the same style of configurable patching as used there, so any unwanted patches can be turned off.

**Comment by Slind14** [comment]
Sounds good. My main concern regarding the collosion fix (and entity list batch remove) was that there might be users that don't want or can't use the multi threading part but would like to use this part. Kinda like nTweaks not being part of TT or ModPatcher.

**Comment by Slind14** [comment]
I thought further about it and believe it would really be better if those non threading related and non critical patches would be in a separated mod. The performance impact of the collision patch and the entity list batch removes are a big improvement on their own. Especially the batch removes as those avoid the annoying lag spikes on base unload. 
From my understanding those wouldn't be too difficult to port. Hence they could probably be used way before the major multi threading is production ready and even on 1.7, if a back porting is manageable.

**Comment by LunNova** [comment]
What about Optifine style core/extra/ultimate (probably got the names wrong) releases?

**Comment by Slind14** [comment]
Like?
- basic (solid proof patches, very unlikely to interfere with mods)
- extra (production ready patches, could be incompatible with some mods)
- ultimate (experimental patches, likely to interfere with mods)

**Comment by LunNova** [comment]
Yes, something like that.
- <_PlaceHolderName_>-core
- <_PlaceHolderName_>-threaded
- <_PlaceHolderName_>-experimental

(TickThreading-threaded really doesn't work as a name)

**Comment by Slind14** [comment]
Do you want something functional (giving an idea of what it does) or creative (no relation, e.g. forge, bukkit, sponge, glowstone). 
Functional I could think of `PerfOverhaul` (performance overhaul). I'm not sure if that is a common word, in my native language it is used in terms of car and machine tuning.

**Comment by LunNova** [comment]
Quick status update:
1. Still working on Mixin - trying hard to avoid the mess the prepatcher was in previous versions
2. Expect to start working on network profiling in TickProfiler by Sunday
3. Vague estimate of starting work on TT proper within two weeks

Still looking for input on the name. I'll make a poll once there are enough good suggestions.

PerfOverhaul - very descriptive, but also quite generic. Not sure if I like it

**Comment by LunNova** [comment]
Ended up working in a slightly different order. Started the work on 1.8.9 TT first, mainly by deleting lots of classes and adding a single Mixin, just to confirm that ModPatcherGradle + ModPatcher + Mixin are working correctly.

Next thing to do is to add network profiling to TP.

My website/jenkins/maven repo may be down for some time due to a hosting migration during the weekend.

**Comment by ProsperCraft** [comment]
Nallar please make a patreon so server owners can give tribute to your greatness :)

**Comment by LunNova** [comment]
Hosting migration is now complete.

> Nallar please make a patreon

Maybe later, once it works.

**Comment by LunNova** [comment]
Status update:

TickProfiler for 1.7.10 and 1.8.9 both have support for all profliing options which TT used to have, except for the `/ticks` command which will continue to be TT only.

After far too much faffing around with classloading (maybe 4 hours?), including ModPatcher's API only in multiple mods of mine now works without conflicts and with automatic updating.

Now to start work on TT!

**Comment by LunNova** [comment]
~~Temporary downtime for nallar.me/jenkins starting in 5 minutes, lasting approximately 15 minutes while I swap the UPS the server is on.~~

Maintenance completed with no issues.

**Comment by LunNova** [comment]
Status update:

Done some work on TT. After starting to actually use the new mixin patching, I ran into some deficiencies mainly involving generics, so more work on JavaTransformer/Mixin was needed to get that working.

I won't be doing much if any work on this over the weekend, as I will be attending [StrathHACK](https://hack.strathtech.co.uk/).

**Comment by LunNova** [comment]
Should have a testing release out by Friday evening GMT. It will not do any threading at all - only a few minor performance improvements.

Goal with this is to find any compatibility issues with the new patching system.

**Comment by Slind14** [comment]
1.8.9 only I suppose?

**Comment by LunNova** [comment]
Yes

**Comment by Slind14** [comment]
Unfortunately I'm not able to offer testing for 1.8.9

**Comment by XPownage** [comment]
@nallar Is the test release going to be out tonight?

**Comment by LunNova** [comment]
Ended up spending more time than expected working on a project for uni, so the testing release will probably be delayed until tomorrow. :(

I want to get the variants system (optifine style multiple release types) implemented as part of the testing release.

Sorry for the delay.

**Comment by XPownage** [comment]
@nallar Its alright, I'd rather want something that you are more conformable with releasing at the end of the day.

**Comment by LunNova** [comment]
[First 1.8.9 testing release!](https://jenkins.nallar.me/job/TickThreading/branch/1.8.9/). Grab the "-core" jar and drop it in your mods folder.

The aim is that it should do: absolutely nothing! A very minor performance improvement by hardcoding the current side in FMLCommonHandler, but nothing substantial.

Hoping to hear that it a) doesn't cause crashes b) has no noticeable impact. This is a test that the new patcher system isn't incompatible. The "-threaded" variant jar will break the game, that's expected.

**Comment by XPownage** [comment]
Awesome! I'll be more than glad to give you input on crashes and other related issues that I might find.

**Comment by XPownage** [comment]
@nallar Ok well I tired launching the core version and it just didn't work.  
28.02 05:58:46 [Server] main/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: me.nallar.modpatcher.ModPatcher$Version

**Comment by LunNova** [comment]
Oops - my test setup had the ModPatcher jar in the mods folder, so it didn't run into that problem. [Should now be fixed](/nallar/ModPatcher/commit/dcfb2ceb72d7c845de6b3a1285867ac6a6eadc81).

**Comment by XPownage** [comment]
Tried it again and yet another crash occurred. 
[net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:48]: Caused by: java.lang.NoClassDefFoundError: me/nallar/modpatcher/ModPatcherTransformer

**Comment by LunNova** [comment]
Can you put the full server log in a gist/pastebin?

**Comment by XPownage** [comment]
@nallar  http://pastebin.com/xxbnU0aX   This log is without other mods just to see if there was conflicts which apparently there wasn't.

**Comment by LunNova** [comment]
@XPownage Great, thanks. It should be fixed in the latest build. I've also added some more detailed logging information for ModPatcher loading.

**Comment by LunNova** [comment]
Sorry for the lack of work this week - a combination of coursework and factorio happened.

ModPatcher updating is now a lot less fragile, so hopefully won't be any more crashes on startup relating to it.

**Comment by XPownage** [comment]
@nallar Tried it again and still crashes, is there any other mods except mod patcher core and tick threading core I need?

**Comment by LunNova** [comment]
@XPownage It shouldn't need any other mods. :s

I think earlier failures may have left some broken files behind in your mods directory. Let's try a clean start.

Delete any files with ModPatcher in their name (eg: ModPatcher.jlib or ModPatcher-core.jar). Ensure the only TT related mod in your mods directory is the latest build, (currently `TickThreading-1.8.9.50-core.jar`).

I've spun up a fresh install of `forge-1.8.9-11.15.1.1764-universal.jar`, dropped in the latest TT build to the mods folder and it's starting up without any problems.

**Comment by LunNova** [comment]
I will now be targeting 1.10. Don't want to get stuck updating past versions again.

**Comment by Slind14** [comment]
makes sense. How is your motivation about this, do you think there will be a production ready version, like 1.4.7 had?

**Comment by ProsperCraft** [comment]
We loved the 1.5.2 version, it worked like a miracle.

**Comment by LunNova** [comment]
@Slind14 I have a reasonable amount of motivation, but too little time. Less motivation than I used to though. :(

I'm trying to do it again, but realistically it's not happening. I expect to continue to have time to keep TickProfiler up to date, but TT is probably never going to be as good as it was when I had near-infinite free time due to being 16 years old!

**Comment by Slind14** [comment]
Thanks for the honesty :)

**Comment by tenten8401** [comment]
Is this still under development? By the way, you should really add a patreon.

**Comment by cpypcy** [comment]
Dude why not TT for 1.7.10? This is where all the mods are! It would be epic if you could make it for that. At least some basic simple version. Just like old times.

**Comment by ghost** [comment]
He's explained this time and time again. I suggest you do some research instead of asking a question that was asked dozens to hundreds of times before.

All in all, TickThreading for MC 1.7.10 is not happening, period.

**Comment by Shybella** [comment]
Yes, please aim for 1.10 it's a very promising version and sustainable. Don't get caught on updating late versions of MC.

**Comment by dotModded** [comment]
How's the progress going Nallar, I'm super interested in this.

**Comment by cpypcy** [comment]
I think going for 1.10.2 was a damn good idea, seems like mods are switching to 1.10.2.

**Comment by tenten8401** [comment]
^

**Comment by LunNova** [comment]
Repo has been moved to a new organisation. Makes sense to not have this under my name, in case anyone else does start helping at some point. :P

Discord chat: https://discordapp.com/invite/YrV3bDm

**Comment by LunNova** [comment]
Quick update:

* Now aiming for 1.12. I'll try to backport a working version to 1.10.2 later if by the time it works 1.10.2 is still popular.
* Working on changing [JavaTransformer](https://github.com/MinimallyCorrect/JavaTransformer) and [Mixin](https://github.com/MinimallyCorrect/Mixin) to allow patching small parts of methods instead of just replacing the entire things. Will allow the old XML based JavaPatcher patches to be dropped completely.

**Comment by dotModded** [comment]
I would wait nallar, 1.13 is a refactor and everything is changing so your mod would be completely broken by then.

**Comment by Slind14** [comment]
1.7.10 is still more popular than 1.10 :D Gonna be interesting to see if 1.10 is able to establish enough to be around for the long run like 1.7.10

**Comment by cpypcy** [comment]
Well 1.7.10 is mod Mecca, making TT for any other version is waste of time sort of, since mods don't seem to like 1.10 or 1.12 much. Once we hit final and last java version, i bet there will be mod insanity and every damn mod that is nod dead will move to that version but i don't see which version will be final java one. Still, better to have some TT than no TT.

**Comment by magneticflux-** [comment]
@cpypcy @Slind14 I'd actually disagree with that assessment at this point in time. I assembled and formatted some mod data from CurseForge to better understand the version situation.

| Version  | Pages of mods | Page Δ (17d) | Days since last release | Link to search |
| --------- | ---------------- | -------- | ------------------------ | ---------------  |
| Total | 417 | +4 | N/A | [Link](https://minecraft.curseforge.com/mc-mods?filter-game-version=) |
| . | | | | |
| `1.7.X` | 211 | +1 | 1148 | [Link](https://minecraft.curseforge.com/mc-mods?filter-game-version=1738749986%3A5) |
| `1.8.X` | 104 | +0 | 617 | [Link](https://minecraft.curseforge.com/mc-mods?filter-game-version=1738749986%3A4) |
| `1.9.X` | 77 | +0 | 464 | [Link](https://minecraft.curseforge.com/mc-mods?filter-game-version=1738749986%3A552) |
| `1.10.X` | 141 | +1 | 420 | [Link](https://minecraft.curseforge.com/mc-mods?filter-game-version=1738749986%3A572) |
| `1.11.X` | 103 | +2 | 239 | [Link](https://minecraft.curseforge.com/mc-mods?filter-game-version=1738749986%3A599) |
| `1.12.X` | 61 | +7 | 14 | [Link](https://minecraft.curseforge.com/mc-mods?filter-game-version=1738749986%3A628) |

I believe that there is a large proportion of `1.7.10` mods that have stopped being developed since their release. To back up my statement, I found that out of all mods with `1.7.X` versions on CurseForge, only 65 pages of them have been modified *at all* since the last `1.11.X` release in December of 2016 ([Link to approximate location in CurseForge list](https://minecraft.curseforge.com/mc-mods?filter-game-version=1738749986:5&filter-sort=updated&page=65)). This tells me that many of those mods are likely to never be updated past `1.7.X` and probably have been superseded by a `1.12.X` mod or abandoned.

I wrote this mainly because I was curious about the statistics and I'd heard other modders debate it before with only anecdotal information. Obviously, this is only current as of 8/17/2017, but I'd expect the balance to shift even further in `1.12.X`'s favor in the future with more Forge updates. Hopefully these statistics will prove to be useful to someone in the future.

---

9/3/2017 Edit:
I have added deltas to each page count that are current as of 9/3/2017. The deltas do not add up because they are rounded to the nearest page and because mods older than `1.7.X` may have changed.

**Comment by Shybella** [comment]
Do not focus on older versions unless you have some magically way to
implement it easier for older versions.

**Comment by Shybella** [comment]
I run a 1.5.2 server and as much as I would like to see a TT for 1.5.2 in
working order I'd rather see development moving forward with new versions.
If TT can recreate some of the magic it did for 1.4.2 and 1.5.2 in 1.10 and
newer. That would be heaven.

**Comment by Slind14** [comment]
Well the latest versions really need it. We just reset an infinity normal server 2 weeks ago. It can still handle +50 players at 40ms, while Age of Engineering/Beyond.. could not even handle 20 players at <80ms during the first weekend. 1.7.10 still performs at least twice as good as 1.10 with less mods.

**Comment by LunNova** [comment]
I've been working on improving Mixin to support injection of code inside existing methods in a flexible way, including the insertion of return or continue statements, or the modification of local variables.

This support is partially implemented, and the following example works: https://github.com/MinimallyCorrect/Mixin/blob/c55b5e464d0cdf6ffdc25de6f077aae0feccda14/src/test/java/org/minimallycorrect/mixin/internal/mixinsource/MixinSource.java

The aim is to significantly reduce the work required implement new patches and to update old patches.

**Comment by Bucky420** [comment]
hummm and where are we on this 1.12...?

**Comment by LunNova** [comment]
We are less ambitious but still rubbish

**Comment by Shybella** [comment]
Sponge just marked 1.12.2 as a LTS version.
